"""Add dice_rolls per lift to program_weeks

Revision ID: b99d2cc395d3
Revises: 17eb3ccd01c4
Create Date: 2025-10-05 23:58:46.211543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b99d2cc395d3'
down_revision = '17eb3ccd01c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_weeks', sa.Column('dice_rolls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('program_weeks', 'dice_roll_1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('program_weeks', 'dice_roll_2',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program_weeks', 'dice_roll_2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('program_weeks', 'dice_roll_1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('program_weeks', 'dice_rolls')
    # ### end Alembic commands ###
