"""Add name field to programs

Revision ID: 17eb3ccd01c4
Revises: 3a6509488a29
Create Date: 2025-10-05 19:32:38.115158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17eb3ccd01c4'
down_revision = '3a6509488a29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'name')
    # ### end Alembic commands ###
