"""Add lift_names to program_configs

Revision ID: da0789f6dfa2
Revises: b99d2cc395d3
Create Date: 2025-10-12 17:55:24.717447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da0789f6dfa2'
down_revision = 'b99d2cc395d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_configs', sa.Column('lift_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_configs', 'lift_names')
    # ### end Alembic commands ###
