"""Add lift weights and intensity RMs to program config

Revision ID: 3a6509488a29
Revises: 6e484a989237
Create Date: 2025-10-05 18:37:45.859102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a6509488a29'
down_revision = '6e484a989237'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_configs', sa.Column('lift_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('program_configs', sa.Column('lift_intensity_rms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_configs', 'lift_intensity_rms')
    op.drop_column('program_configs', 'lift_weights')
    # ### end Alembic commands ###
